name: workflow run
on:
  workflow_run:
    workflows:
      - foo
    types:
      - completed

jobs:
  only-run-on-fork-or-master:
    # Only execute this check when a PR is opened from a fork rather than the upstream repo OR master
    # head_repository is *only* available when run within workflow_run (use github.event.pull_request for PRs)
    if: github.event.workflow_run.head_repository.full_name != 'getsentry/github-actions-testing'
    name: Run only on forks
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Hello fork master
        run: |
          echo "Hello fork or master!"

  # only-run-on-upstream:
  #   # Opposite of above
  #   if: github.ref != 'refs/heads/master' && github.event.workflow_run.head_repository.full_name == 'getsentry/github-actions-testing'
  #   name: Run only on upstream
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 5
  #   steps:
  #     - name: Hello upstream
  #       run: |
  #         echo "Hello upstream!"

  # run-on-success:
  #   # https://docs.github.com/en/enterprise-server@3.2/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
  #   if: github.event.workflow_run.conclusion == 'success'
  #   name: workflow run
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 5
  #   steps:
  #     - name: Hello world
  #       run: |
  #         echo "Hello world!"

  # run-on-failure:
  #   # https://docs.github.com/en/enterprise-server@3.2/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
  #   if: github.event.workflow_run.conclusion == 'failure'
  #   name: workflow run
  #   runs-on: ubuntu-20.04
  #   timeout-minutes: 5

  #   steps:
  #     - name: Hello world
  #       run: |
  #         echo "Hello world!"
