name: workflow run context
on:
  workflow_run:
    workflows:
      - foo
    types:
      - completed

jobs:
  workflow-run:
    name: GH context
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Github context
        run: |
          jq . <<EOF
            ${{ toJSON(github) }}
          EOF
